name: Build and Upload Mod

on:
  push:
    branches:
      - 1.21  # 1.21ブランチ限定
    tags:
      - '*'   # タグpushも検知する

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy built JAR to versioned folder
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          mkdir -p jar
          cp build/libs/*.jar "jar/${VERSION}.jar"

      - name: Commit and push JAR
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add jar/${GITHUB_REF#refs/tags/}.jar
          git commit -m "Add jar for ${GITHUB_REF#refs/tags/}"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
