name: Fix TConX Material Stat Paths

on:
  workflow_dispatch:

jobs:
  relocate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Move all material stat files to tconx path
      run: |
        SRC_DIR="src/main/resources/data/tconstruct/materials/stats"
        DEST_DIR="src/main/resources/data/tconx/tconstruct/materials/stats"

        if [ -d "$SRC_DIR" ]; then
          mkdir -p "$DEST_DIR"
          mv "$SRC_DIR"/* "$DEST_DIR"/
          echo "Moved files from $SRC_DIR to $DEST_DIR"
        else
          echo "No files found in $SRC_DIR"
        fi

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and push
      run: |
        git add -A
        git commit -m "fix: move TConX stat files to correct path" || echo "No changes to commit"
        git push
