name: Add Gradle Wrapper (main branch)

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  add-gradlew:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.9

      - name: Commit and push Gradle Wrapper
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          [ -f gradlew ] && git add gradlew
          [ -f gradlew.bat ] && git add gradlew.bat
          [ -f gradle/wrapper/gradle-wrapper.jar ] && git add gradle/wrapper/gradle-wrapper.jar
          [ -f gradle/wrapper/gradle-wrapper.properties ] && git add gradle/wrapper/gradle-wrapper.properties
          git commit -m "Add Gradle Wrapper files (via GitHub Actions)" || echo "No changes to commit"
          git push
