name: Add Gradle Wrapper (main branch)

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  add-gradlew:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Gradle 8.9 をセットアップ（システムのGradle 9.xを回避）
      - name: Set up Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Generate Gradle Wrapper (8.9)
        run: |
          gradle wrapper --gradle-version 8.9

      - name: Commit and push Gradle Wrapper
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties
          git commit -m "Add Gradle Wrapper files (via GitHub Actions)" || echo "No changes to commit"
          git push
