name: Fetch and Upload File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 毎日 3:00 UTC に実行（任意）

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Download file via curl
        run: |
          curl -L -o wra.jar https://raw.githubusercontent.com/quek04/undergarden/1.20/gradle/wrapper/gradle-wrapper.jar
          curl -L -o wra.properties https://raw.githubusercontent.com/quek04/undergarden/1.20/gradle/wrapper/gradle-wrapper.properties 

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add wra.jar wra.properties
          git commit -m "Update target_file.txt from external repo" || echo "No changes to commit"
          git push
