name: Build and Upload Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Modpackリポジトリをチェックアウト
      - name: Checkout Modpack repository
        uses: actions/checkout@v3

      # 2. Tconxリポジトリのsrcフォルダだけを上書きコピー
      - name: Checkout Tconx src
        uses: actions/checkout@v3
        with:
          repository: Konnitiwa768/Tconx
          ref: 1.21 # 必要なブランチ名に変更
          sparse-checkout: |
            src
          path: tconx-src

      - name: Overwrite src directory
        run: |
          rm -rf src
          cp -r tconx-src/src ./src

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
