name: Build and Upload Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Modpack repository
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      # === ここでJARファイルをアーティファクトとしてアップロード ===
      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar

      # --- cf-uploaderによるCurseForge自動アップロード ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cf-uploader
        run: pip install cf-uploader

      - name: Upload to CurseForge (cf-uploader)
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CF_API_KEY }}
        run: |
          latest_jar=$(ls build/libs/*.jar | sort -V | tail -n1)
          cf-uploader upload \
            --api-key "$CURSEFORGE_API_KEY" \
            --project-id 684215 \
            --file-path "$latest_jar" \
            --changelog "自動ビルド & アップロード" \
            --game-version "1.20.1" \
            --release-type "release"
