name: Build Mod!

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v1.0'  # タグが push されたときにも実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download loom-1.9.428.jar
        run: |
          mkdir -p libs
          curl -L -o libs/loom-1.9.428.jar https://maven.architectury.dev/dev/architectury/loom/1.9.428/loom-1.9.428.jar

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --info --refresh-dependencies --stacktrace

      - name: Upload to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release!
          tag_name: v1.0
          files: build/libs/tconx-1.0.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
